name: Bug Report
description: Report a bug or unexpected behaviour in the MCP Connector Template
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug!
        Please fill in as much detail as possible to help us reproduce and fix the issue.
        **For security vulnerabilities, do NOT open a public issue — see [SECURITY.md](../../SECURITY.md) instead.**

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: "When I do X, Y happens instead of Z."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behaviour.
      placeholder: |
        1. Run `dotnet run --project Mcp.Connector.Template`
        2. Send request `curl ...`
        3. Observe error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
      description: What actually happened? Include error messages and stack traces if available.
    validations:
      required: true

  - type: input
    id: dotnet_version
    attributes:
      label: .NET SDK version
      description: Output of `dotnet --version`
      placeholder: "10.0.x"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Linux
        - macOS
        - Windows
        - Docker (Linux container)
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other information that might be relevant (logs, configuration, related issues, etc.)
